query ($name: String!, $passwd: String!) {
  Person {
    token(name: $name, passwd: $passwd) {
      header {
        code
      }
      body {
        name
        token
        flag
      }
    }
  }
}