query ($stockId: Int) {
    Person {
        stockData(stockId: $stockId) {
            header {
                code
                text
            }
            body {
                stockId
                total
                price
                updated
            }
        }
    }
}